
```{r}
#| label: setup air leakage data
#| echo: false
#Load Data
Energy_Audits <- read_excel("../data/Energy_Audit_template.xlsx")

Building_Audit <- Energy_Audits |>
  filter(Adress_Name == params$adress) # Auditor_full_name == params$Auditor_full_name

ACHn <- Building_Audit |>
  select("Natural Air Changes per Hour(ACHn)")|>
  mutate()
ACHn1 <- data.frame(IdialACHn = c("Ideal"))
airleakdata <- cbind(ACHn,ACHn1)  
```

```{r}
#| label: ACHn ggplot
#| warning: false
#| echo: false

ggplot(Building_Audit, aes(y=1))+
  geom_bar(width=1, fill ="transparent")+ #add8e6
  #scale_fill_gradient(low="#FF8888",high="#FF0000")+ #it should be working idk why it doesn't
  geom_vline(xintercept= c(0, 0.04, 0.35, 0.41, 0.6,1), size= 1.3, ylim)+
  geom_vline(xintercept=2.44, #move this to before previous x intercepts
                linetype=1, colour="blue", size= 1.3)+ #(maybe have coditional color? red if ACHn is to big blue if it's ok)
  #scale_x_reverse()+
  
#The vline text lables
  geom_text(aes(x=2.44, label="Your Home", y=1), nudge_x= -0.03, colour="blue", angle=90, text=element_text(size=11)) + #move this to the legend
  geom_text(aes(x=0, label="", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.04, label="Passive House", y=1), nudge_x= -0.02, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.35, label="Very Tight Mechanical \nVentilation Needed", y=1), nudge_x= -0.05, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.41, label="Tight", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.6, label="Leaky", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=1, label="Very Leaky", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  
#The vline text values 
  geom_text(aes(x=2.44, label=2.44, y=1.55), nudge_x= -0.03,nudge_y = -1, colour="blue", angle=90, text=element_text(size=11)) + #move this to the legend
  geom_text(aes(x=0, label="0", y=1.55), nudge_x= -0.03,nudge_y = -1.0323, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.04, label="0.04", y=1.55), nudge_x= -0.02, nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.35, label="0.35", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.41, label="0.41", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.6, label="0.6", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=1, label="1", y=1.55), nudge_x= -0.03,nudge_y = -1.03, colour="black", angle=90, text=element_text(size=11)) +
  theme_void()
ggsave("GCI_2_44.png", width=15, height=5)
#Here will be a singular bar plat with air leak visualization
```

```{r}
#| label: ACH50 ggplot
#| warning: false
#| echo: false

ggplot(airleakdata, aes(y=IdialACHn))+
  geom_bar(width=1, fill ="#add8e6")+
  #scale_fill_gradient(low="#FF8888",high="#FF0000")+ #it should be working idk why it doesn't
  geom_vline(xintercept= c(0, 0.70, 6, 7, 10.5, 17.5), size= 1.3, ylim)+
  geom_vline(xintercept=16.7,
                linetype=1, colour="blue", size= 1.3)+ #(maybe have coditional color? red if ACHn is to big blue if it's ok)
  #scale_x_reverse()+
  
#The vline text lables
  geom_text(aes(x=16.7, label="Your Home", y=1), nudge_x= -0.03, colour="blue", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0, label="", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.04, label="Passive House", y=1), nudge_x= -0.02, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.35, label="Very Tight Mechanical \nVentilation Needed", y=1), nudge_x= -0.05, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.41, label="Tight", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.6, label="Leaky", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=1, label="Very Leaky", y=1), nudge_x= -0.03, colour="black", angle=90, text=element_text(size=11)) +
  
#The vline text values 
  geom_text(aes(x=16.7, label=16.7, y=1.55), nudge_x= -0.03,nudge_y = -1, colour="blue", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0, label="0", y=1.55), nudge_x= -0.03,nudge_y = -1.0323, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.04, label="0.04", y=1.55), nudge_x= -0.02, nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.35, label="0.35", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.41, label="0.41", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=0.6, label="0.6", y=1.55), nudge_x= -0.03,nudge_y = -1, colour="black", angle=90, text=element_text(size=11)) +
  geom_text(aes(x=1, label="1", y=1.55), nudge_x= -0.03,nudge_y = -1.03, colour="black", angle=90, text=element_text(size=11)) +
  theme_void()
#Here will be a singular bar plat with air leak visualization
```