---
title: "Energy Report"
author: "Need the df & column name"
date: '`{r} Sys.Date()`'
format: html
editor: visual
---

## \[Enter address and/or family name here\] Pre-Improvements report 

## Building general info

Build: #Need the df & column name

Area: #Need the df & column name

Heating type: #Need the df & column name

etc. :

## Buildings Electricy use

```{r}
#| echo: true
#| warning: false
library(readxl)
library(tidyverse)
Sys.Date()
```

```{r}
#| echo: false
#| warning: false
#Need to have correct df
table_heating_oil_case_study <- read_excel("../data/table_heating_oil_case_study.xlsx")

table_electricity_case_study <- read_excel("../data/table_electricity_case_study.xlsx")
```

```{r}
#| echo: false
# need ton have correct df
Carriage_heating_oil <- table_heating_oil_case_study |>
  filter(Building == "Carriage") |> #need correct filter 
  mutate()

Carriage_electricity <- table_electricity_case_study |>
  filter(Building == "Carriage  House") |>
  mutate()
```

```{r}
#| echo: false
#| warning: false
ggplot() +
  geom_line(Carriage_heating_oil, mapping = aes(x = `Delivery Date`, y = Gallons), color = "blue") + 
  geom_line(Carriage_electricity, mapping = aes(x = Month, y = KWH), color = "red") +
  scale_y_continuous(
    name = "Gallons",
    sec.axis = sec_axis(trans = ~.*1, name="kWh"))+
  geom_vline(xintercept=as.POSIXct(as.Date("2021-08-01")),
                linetype=3, colour="black") +
   annotate("text", x=as.POSIXct(as.Date("2021-06-01")), y=600, label="David started as the Director of Energy", angle=90) +
  geom_vline(xintercept=as.POSIXct(as.Date("2019-09-01")),
                linetype=3, colour="black") +
   annotate("text", x=as.POSIXct(as.Date("2019-07-01")), y=400, label="Electricity Data collection sarted", angle=90)+
  theme(axis.title.y.left = element_text(colour = "blue"),axis.title.y.right = element_text(colour = "red" ))+
  labs(title = "Carriage's house energy history", subtitle = "Gallons of heating oil and kWh of electricity")
```
