project:
  type: website

website:
  title: "Home Energy Imrovements project"
  navbar:
    tools:
      - icon: github
        href: https://github.com/LaurieLBaker/CEDS-Energy
      - icon: Community Energy Center
        href: https://www.coa.edu/cec/
    left:
      - href: index.qmd
        text: About
      - communities.qmd
      - text: "More"
        menu:
          - talks.qmd
          - about.qmd 
          - more.qmd
         #worked before, stopped working
      
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

