project:
  type: website

website:
  title: "Home Energy Improvements projects"
  navbar:
    tools:
      - icon: globe2
        text: Community Energy Center
        href: https://www.coa.edu/cec/
      - icon: github
        href: https://github.com/LaurieLBaker/CEDS-Energy
      
    left:
      - href: index.qmd
        text: About
      - communities.qmd
      - href: goals.qmd
        text: Goals
      - href: more.qmd
        text: Questions
      - text: "More"
        menu:
          - href: more.qmd
            text: Questions
         #worked before, stopped working
  page-footer: 
    background: gray
    left: "Copyright 2024, Someone" 
    center: "Made with quarto"
    right: "Build during Community Engaged Data Science Class"
    
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

