project:
  type: website

website:
  title: "Home Energy Imrovements project"
  navbar:
    tools:
      - icon: github
        href: https://github.com/LaurieLBaker/CEDS-Energy
    left:
      - href: index.qmd
        text: About
      - communities.qmd
      - more.qmd
         #worked before, stopped working
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

