---
title: "About"
format: html
editor: visual
---

# Local background

Maine is the most heating-oil dependent state in the country, with 58% of homes using fuel oil as the primary source of heat (EIA). Maine does not have any fossil fuel reserves or extraction. In recent years, we have spent more than \$4 billion annually on fossil fuels, resulting in more than 6% of the gross state product leaving the state each year for energy imports. In the last two years, heating oil and kerosene prices doubled from \$2-\$3/gallon (January 2015-January 2022) to \$5-6/gallon, and stayed above \$4/gallon for the entire year from March 2022 to March 2023. At the same time, Maine’s electric prices increased significantly, causing already high household energy burdens to nearly double in the last two years.

Maine has some of the oldest houses in the nation. 24% of homes were built before 1939, 32% were built from 1940 to 1979. Unfortunately, most homes built since 1980 are not well insulated either. As Maine has enacted a statewide Climate Action Plan, we have encountered significant workforce shortages, particularly in the energy efficiency and weatherization sector. The state has identified doubling the energy efficiency workforce as a priority for reaching clean energy goals.

# This program

The energy team at College of the Atlantic, headed by David Gibson, recently received a grant from the U.S. Department of Energy Building Technologies Office to fund a program making home energy improvements more accessible to coastal Maine homeowners. Participating households will receive upgrades to critical areas of their homes, such as heating and cooling systems, lighting, insulation, and air sealing, in addition to potential solar arrays. The upgrade process begins with an in-depth audit of the current systems installed in groups of 10 or more buildings, and identifying the upgrades that would provide the most benefit in comfort and energy efficiency. From there, the team will coordinate with contractors on the behalf of the homeowners to install these measures.

In addition to the team organizing energy upgrades, this project also involves a data science team to quantitatively analyze the benefit provided by the installed upgrades using temperature and heating load data. The team will also analyze data collected from the Arduino air quality monitors installed in consenting households, both to visualize the effectiveness of the energy upgrades and to identify potential air quality risks to be corrected.

### **References:**

-   EIA. <https://www.eia.gov/state/data.php?sid=ME#ConsumptionExpenditures>. Accessed on Feb 6, 2024.
